### ISSUE TITLE
Zoom in/out via mouse wheel does not work.

### ISSUE THREAD

**Issue by FreshnessDND** [manuelVo/foundryvtt-catch-up#1]
I completely understand that this isn't a fully completed and released module. I have been troubleshooting on the foundry discord for sometime as I had a bug in 8.9 and now 9.242 that resulted in tokens not downloaded for those players still loading into world or scene. I was referred to this bug posting, https://gitlab.com/foundrynet/foundryvtt/-/issues/5624, and found this module through that.

I have play tested the module even though I can't zoom in/out with the scroll wheel. I had no errors or conflicts running several encounters and swamping the map with tokens. I tried to replicate the issue through three clients (gm, player, player). Only one time did I have a single token out of many that did not download for client.

This bug is a much bigger issue than people realize. As Foundry develops, worlds are going to become larger and more complicated making it a big deal.

I hope you continue to develop this and push to have it a core module.

Thank you.

**Comment by manuelVo** [comment]
This turned out to be an incompatibility of older versions of the module with Foundry 9
