### ISSUE TITLE
V10

### ISSUE THREAD

**Issue by Cosmic-Lattee** [manuelVo/foundryvtt-catch-up#2]
So the error (https://github.com/foundryvtt/foundryvtt/issues/5624) is still around and wont likely be fixed anytime soon.

However it seems like the v10 update broke this module. 

![image](https://user-images.githubusercontent.com/24766235/195723407-e8a45769-c104-4324-97b5-cd09d1742c7a.png)

Not sure how difficult a fix this would be, and thank you for your work on this! :)

**Comment by manuelVo** [comment]
Unfortunately, this module needs to be updated for every single major release of FoundryVTT. As far as porting it to v10 goes, it's currently very far down on my priority list, since it's used by barely anyone. However, it's very likely that it'll be ported eventually.

**Comment by Cosmic-Lattee** [comment]
I totally understand that. Very unfortunate that it is something each update breaks, I don't envy you with that. Please do take your time, I just made this in case you weren't aware since this isn't something most people use.

I got a lot of milage out of it because I play a lot of duo games with my wife, and I will often forget to wait before moving things as she is loading in.

Thanks again!
